baseURL = 'https://ken-chy129.github.io/wiki/'
languageCode = 'zh-cn'
title = 'Personal Wiki'

[module]
  [[module.imports]]
    path = 'github.com/alex-shpak/hugo-book'

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
